### ISSUE TITLE
Add splash screen with animation

### ISSUE THREAD

**Issue by Iikeli** [NiftyTreeStudios/Bean-Juice#54]

**Comment by pankova** [comment]
Hi! The task needs not only the development, but the design, doesn't it?

**Comment by Iikeli** [comment]
@pankova yes, this task also needs a design, I'll assign this to myself as I already have an idea in my head.

**Comment by Iikeli** [comment]
Solved with 4b0a6c55b9101f44a66952d276386ee4042be190
