### ISSUE TITLE
Color picker for custom accent color

### ISSUE THREAD

**Issue by Iikeli** [NiftyTreeStudios/Bean-Juice#98]
Add a color picker for the custom accent color

**Comment by pankova** [comment]
Hi! The project is great. I'm a fan of Aeropress and V60. If you don't mind, I'd like to help with the issue.

**Comment by Iikeli** [comment]
Hi @pankova !

You are very welcome to help with this! The one issue is that currently the main branch might not be in a usable state. I did some odd things when taking the CocoaPods integration out and haven't had the time to fully fix that. So if you run into any problems with that, just let me know and I'll allocate some time for fixing that.

**Comment by AlexBurneikis** [comment]
I believe I have done it! PR incoming!

**Comment by pankova** [comment]
Great! Maybe I can help with another task!
